import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthButtons from "./components/AuthButtons";
import Providers from "./providers";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Let's learn Next!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" className={poppins.variable}>
      <Providers>
        <body
          className="antialiased"
        >
          <AuthButtons />
          {children}
        </body>
      </Providers>
    </html>
  );
}
